name = "client"
type = "javascript"
zone_id = ""
account_id = "b4634902249fe28a3f39234db9bb371a"
route = ""
workers_dev = true
compatibility_date = "2021-09-30"

kv_namespaces = [
  { binding = "RECORDS", preview_id = "a0f1e11b7ead4af2bb208059c4240c09", id = "b1cb210d3a624b96ab1597f8491ebc11" },
  { binding = "BLOCKS", preview_id = "d6b0ab503d3a4ad3b869a1066524bbb9", id = "d9e684c5c2c0421aa8ae802df4178460" }
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"
# bundle to publish is package.main = dist/index.min.js

# [secrets]
# PEER_PRIVKEY
# FIL_PRIVKEY
# NOISE_PRIVKEY
